server:
  port: 8083

spring:
  application:
    name: recruit-ai-demo

  ai:
    openai:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-v4-pro

logging:
  level:
    org.springframework.ai: INFO
    com.whlg.ai.demo: DEBUG