server:
  port: 8083

spring:
  application:
    name: recruit-ai-demo

  ai:
    openai:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        api-key: ${DEEPSEEK_API_KEY}
        options:
          model: deepseek-v4-pro
      embedding:
        base-url: https://dashscope.aliyuncs.com/compatible-mode
        api-key: ${DASHSCOPE_API_KEY}
        options:
          model: text-embedding-v2
    vectorstore:
      milvus:
        client:
          host: localhost
          port: 19530
        collectionName: recruit_knowledge_base
        embeddingDimension: 1536
        initialize-schema: true

logging:
  level:
    org.springframework.ai: INFO
    com.whlg.ai.demo: DEBUG