server:
  port: 8082

spring:
  application:
    name: recruit-ai-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/recruit_smart?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ${SQL_PASSWORD}

  ai:
    openai:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        api-key: ${DEEPSEEK_API_KEY}
        options:
          model: deepseek-v4-pro
      embedding:
        base-url: https://dashscope.aliyuncs.com/compatible-mode
        api-key: ${DASHSCOPE_API_KEY}
        options:
          model: text-embedding-v2
    vectorstore:
      milvus:
        client:
          host: localhost
          port: 19530
        collectionName: recruit_ai_service_kb_v3
        embeddingDimension: 1536
        initialize-schema: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.recruit.ai.mapper: debug

knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-swagger-models: true
    enable-document-manage: true
    enable-version: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
