server:
  port: 8080
spring:
  application:
    name: service-biz
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/recruit_smart?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.recruit.biz.mapper: debug