import { getApplicationStatusText, getScreeningDecisionStatus } from '@/config/pipeline'
import type {
  PipelineApplication,
  PipelineQuery,
  PipelineReviewRequest,
  PipelineStatusUpdateRequest,
} from '@/types/pipeline'

export const initialDemoPipeline: PipelineApplication[] = [
  {
    id: 501,
    candidateId: 211,
    candidateName: '林一凡',
    candidatePhone: '13900000211',
    education: '硕士',
    school: '浙江大学',
    yearsOfExperience: 5,
    resumeId: 601,
    resumeName: '林一凡-设计系统负责人简历',
    jobId: 103,
    jobTitle: 'UI/UX 设计师',
    department: '产品设计部',
    status: 'SCREENING',
    statusText: '筛选中',
    source: 'ONLINE',
    sourceText: '官网投递',
    allowAdjustment: true,
    ownerName: '周倩',
    appliedAt: '2026-07-15T08:40:00',
    lastActivityAt: '2026-07-15T11:30:00',
    hrNote: '作品集完整，需要核实跨团队推动范围。',
    rejectReasonCode: null,
    rejectReason: null,
    reviewDecision: 'PENDING',
    aiMatch: {
      score: 92,
      level: 'HIGH',
      summary: '企业产品设计和设计系统建设经历与岗位要求高度相关。',
      highlights: ['主导过多产品线设计系统', '具备复杂工作台项目经验'],
      risks: ['人员管理范围尚未从简历中得到充分验证'],
      suggestion: '建议在面试中核实设计治理指标和跨团队推动方法。',
      modelName: 'demo-model',
      generatedAt: '2026-07-15T08:45:00',
    },
    interview: null,
    offer: null,
    timeline: [
      {
        id: '501-ai',
        title: '生成岗位匹配参考',
        description: '输出 92 分匹配参考与 1 项待核实风险。',
        actorName: 'demo-model',
        occurredAt: '2026-07-15T08:45:00',
        source: 'AI',
        relatedObject: 'UI/UX 设计师',
      },
      {
        id: '501-screening',
        title: '进入 HR 筛选',
        description: '周倩开始审核候选人资料。',
        actorName: '周倩',
        occurredAt: '2026-07-15T11:30:00',
        source: 'BUSINESS',
        relatedObject: '投递 #501',
      },
    ],
  },
  {
    id: 502,
    candidateId: 212,
    candidateName: '赵可欣',
    candidatePhone: '13900000212',
    education: '本科',
    school: '同济大学',
    yearsOfExperience: 3,
    resumeId: 602,
    resumeName: '赵可欣-AI 产品设计简历',
    jobId: 103,
    jobTitle: 'UI/UX 设计师',
    department: '产品设计部',
    status: 'SUBMITTED',
    statusText: '已投递',
    source: 'ONLINE',
    sourceText: '官网投递',
    allowAdjustment: false,
    ownerName: null,
    appliedAt: '2026-07-15T10:50:00',
    lastActivityAt: '2026-07-15T10:50:00',
    hrNote: null,
    rejectReasonCode: null,
    rejectReason: null,
    reviewDecision: null,
    aiMatch: {
      score: 86,
      level: 'HIGH',
      summary: '产品设计基础符合岗位要求，AI 产品经验具有相关性。',
      highlights: ['有企业 SaaS 项目经验', '作品集结构完整'],
      risks: ['设计系统经验深度需要进一步确认'],
      suggestion: '建议由 HR 阅读作品集后再决定是否进入面试。',
      modelName: 'demo-model',
      generatedAt: '2026-07-15T10:55:00',
    },
    interview: null,
    offer: null,
    timeline: [
      {
        id: '502-submit',
        title: '候选人提交投递',
        description: '使用“AI 产品设计简历”投递该职位。',
        actorName: '赵可欣',
        occurredAt: '2026-07-15T10:50:00',
        source: 'BUSINESS',
        relatedObject: 'UI/UX 设计师',
      },
    ],
  },
  {
    id: 503,
    candidateId: 201,
    candidateName: '张晨',
    candidatePhone: '13900000101',
    education: '本科',
    school: '武汉理工大学',
    yearsOfExperience: 3,
    resumeId: 301,
    resumeName: '张晨-Java 后端简历',
    jobId: 101,
    jobTitle: 'Java 后端开发工程师',
    department: '技术部',
    status: 'INTERVIEWING',
    statusText: '面试中',
    source: 'ONLINE',
    sourceText: '官网投递',
    allowAdjustment: true,
    ownerName: '周倩',
    appliedAt: '2026-07-12T09:20:00',
    lastActivityAt: '2026-07-15T09:20:00',
    hrNote: '技术栈匹配，已安排一面。',
    rejectReasonCode: null,
    rejectReason: null,
    reviewDecision: 'PASS',
    aiMatch: {
      score: 88.5,
      level: 'HIGH',
      summary: '技术栈与岗位要求匹配，相关业务项目经历较完整。',
      highlights: ['熟悉 Spring Boot 与 MySQL', '具备招聘系统相关项目经历'],
      risks: ['复杂业务建模深度仍需面试核实'],
      suggestion: '建议结合项目细节和系统设计题进一步验证。',
      modelName: 'demo-model',
      generatedAt: '2026-07-12T09:25:00',
    },
    interview: {
      id: 701,
      round: '一面',
      interviewerName: '陈明',
      interviewTime: '2026-07-16T14:00:00',
      method: 'ONLINE',
      location: '腾讯会议 123-456-789',
      status: 'SCHEDULED',
      statusText: '待面试',
      feedbackScore: null,
      feedbackSuggestion: null,
    },
    offer: null,
    timeline: [
      {
        id: '503-pass',
        title: 'HR 确认初筛通过',
        description: '审核候选人简历与 AI 参考后，由 HR 决定推进。',
        actorName: '周倩',
        occurredAt: '2026-07-14T16:30:00',
        source: 'BUSINESS',
        relatedObject: '投递 #503',
      },
      {
        id: '503-interview',
        title: '创建一面安排',
        description: '面试官陈明，线上面试。',
        actorName: '周倩',
        occurredAt: '2026-07-15T09:20:00',
        source: 'BUSINESS',
        relatedObject: '面试 #701',
      },
    ],
  },
  {
    id: 504,
    candidateId: 204,
    candidateName: '陈思悦',
    candidatePhone: '13900000104',
    education: '本科',
    school: '江南大学',
    yearsOfExperience: 6,
    resumeId: 305,
    resumeName: '陈思悦-产品设计作品集',
    jobId: 103,
    jobTitle: 'UI/UX 设计师',
    department: '产品设计部',
    status: 'SCREEN_PASS',
    statusText: '初筛通过',
    source: 'ONLINE',
    sourceText: '招聘网站',
    allowAdjustment: false,
    ownerName: '周倩',
    appliedAt: '2026-07-13T14:10:00',
    lastActivityAt: '2026-07-15T10:10:00',
    hrNote: '作品集完整，等待确认面试官时间。',
    rejectReasonCode: null,
    rejectReason: null,
    reviewDecision: 'PASS',
    aiMatch: {
      score: 84,
      level: 'HIGH',
      summary: '企业产品与设计系统经验符合岗位重点。',
      highlights: ['复杂工作台经验', '设计系统建设经验'],
      risks: ['团队管理范围需要进一步核实'],
      suggestion: '建议结合真实作品和跨团队协作案例判断。',
      modelName: 'demo-model',
      generatedAt: '2026-07-13T14:15:00',
    },
    interview: null,
    offer: null,
    timeline: [
      {
        id: '504-pass',
        title: 'HR 确认初筛通过',
        description: '下一步需要创建面试安排。',
        actorName: '周倩',
        occurredAt: '2026-07-15T10:10:00',
        source: 'BUSINESS',
        relatedObject: '投递 #504',
      },
    ],
  },
  {
    id: 505,
    candidateId: 213,
    candidateName: '周雯',
    candidatePhone: '13900000213',
    education: '本科',
    school: '北京邮电大学',
    yearsOfExperience: 4,
    resumeId: 603,
    resumeName: '周雯-前端工程师简历',
    jobId: 104,
    jobTitle: '前端开发工程师',
    department: '技术部',
    status: 'OFFER',
    statusText: 'Offer 阶段',
    source: 'REFERRAL',
    sourceText: '员工推荐',
    allowAdjustment: true,
    ownerName: '李然',
    appliedAt: '2026-07-05T09:30:00',
    lastActivityAt: '2026-07-15T10:05:00',
    hrNote: 'Offer 已发送，等待候选人回复。',
    rejectReasonCode: null,
    rejectReason: null,
    reviewDecision: 'PASS',
    aiMatch: null,
    interview: {
      id: 702,
      round: '二面',
      interviewerName: '刘晓',
      interviewTime: '2026-07-12T15:00:00',
      method: 'OFFLINE',
      location: '武汉研发中心 3A',
      status: 'COMPLETED',
      statusText: '已完成',
      feedbackScore: 89,
      feedbackSuggestion: 'PASS',
    },
    offer: {
      id: 801,
      salary: 18000,
      entryDate: '2026-08-01',
      workLocation: '武汉',
      status: 'SENT',
      statusText: '已发送',
    },
    timeline: [
      {
        id: '505-offer',
        title: 'HR 发送 Offer',
        description: '候选人尚未接受或拒绝。',
        actorName: '李然',
        occurredAt: '2026-07-15T10:05:00',
        source: 'BUSINESS',
        relatedObject: 'Offer #801',
      },
    ],
  },
  {
    id: 506,
    candidateId: 214,
    candidateName: '魏然',
    candidatePhone: '13900000214',
    education: '硕士',
    school: '华中科技大学',
    yearsOfExperience: 5,
    resumeId: 604,
    resumeName: '魏然-视觉交互设计简历',
    jobId: 103,
    jobTitle: 'UI/UX 设计师',
    department: '产品设计部',
    status: 'HIRED',
    statusText: '已入职',
    source: 'REFERRAL',
    sourceText: '员工推荐',
    allowAdjustment: false,
    ownerName: '周倩',
    appliedAt: '2026-06-20T10:00:00',
    lastActivityAt: '2026-07-15T09:00:00',
    hrNote: '候选人已接受 Offer，入职材料审核中。',
    rejectReasonCode: null,
    rejectReason: null,
    reviewDecision: 'PASS',
    aiMatch: null,
    interview: null,
    offer: {
      id: 802,
      salary: 19000,
      entryDate: '2026-07-19',
      workLocation: '上海',
      status: 'ACCEPTED',
      statusText: '已接受',
    },
    timeline: [
      {
        id: '506-accept',
        title: '候选人接受 Offer',
        description: '系统进入入职材料准备阶段。',
        actorName: '魏然',
        occurredAt: '2026-07-15T09:00:00',
        source: 'BUSINESS',
        relatedObject: 'Offer #802',
      },
    ],
  },
  {
    id: 507,
    candidateId: 203,
    candidateName: '王嘉禾',
    candidatePhone: '13900000103',
    education: '本科',
    school: '湖北大学',
    yearsOfExperience: 4,
    resumeId: 304,
    resumeName: '王嘉禾-HR 简历',
    jobId: 101,
    jobTitle: 'Java 后端开发工程师',
    department: '技术部',
    status: 'SCREEN_REJECT',
    statusText: '初筛未通过',
    source: 'HR_IMPORT',
    sourceText: 'HR 录入',
    allowAdjustment: false,
    ownerName: '周倩',
    appliedAt: '2026-07-14T16:40:00',
    lastActivityAt: '2026-07-14T17:20:00',
    hrNote: '与目标岗位技术方向不匹配。',
    rejectReasonCode: 'SKILL_NOT_MATCH',
    rejectReason: '缺少 Java、Spring Boot 和数据库开发经验。',
    reviewDecision: 'REJECT',
    aiMatch: {
      score: 35,
      level: 'LOW',
      summary: '主要经历集中在人力资源方向，与后端岗位要求差距较大。',
      highlights: ['招聘流程与沟通经验较完整'],
      risks: ['缺少 Java、Spring Boot 和数据库开发经验'],
      suggestion: '该结果仅作为岗位匹配参考，拒绝原因仍需由 HR 审核记录。',
      modelName: 'demo-model',
      generatedAt: '2026-07-14T16:45:00',
    },
    interview: null,
    offer: null,
    timeline: [
      {
        id: '507-reject',
        title: 'HR 结束投递流程',
        description: '拒绝原因：核心技能不匹配。',
        actorName: '周倩',
        occurredAt: '2026-07-14T17:20:00',
        source: 'BUSINESS',
        relatedObject: '投递 #507',
      },
    ],
  },
  {
    id: 508,
    candidateId: 215,
    candidateName: '顾知行',
    candidatePhone: '13900000215',
    education: '本科',
    school: '南京理工大学',
    yearsOfExperience: 2,
    resumeId: 605,
    resumeName: '顾知行-Java 工程师简历',
    jobId: 101,
    jobTitle: 'Java 后端开发工程师',
    department: '技术部',
    status: 'WITHDRAWN',
    statusText: '已撤回',
    source: 'ONLINE',
    sourceText: '官网投递',
    allowAdjustment: false,
    ownerName: null,
    appliedAt: '2026-07-10T11:00:00',
    lastActivityAt: '2026-07-12T18:20:00',
    hrNote: null,
    rejectReasonCode: 'CANDIDATE_WITHDRAW',
    rejectReason: '候选人已接受其他公司的录用邀请。',
    reviewDecision: null,
    aiMatch: null,
    interview: null,
    offer: null,
    timeline: [
      {
        id: '508-withdraw',
        title: '候选人撤回投递',
        description: '候选人主动结束本次投递。',
        actorName: '顾知行',
        occurredAt: '2026-07-12T18:20:00',
        source: 'BUSINESS',
        relatedObject: '投递 #508',
      },
    ],
  },
]

export function getDemoPipelinePage(records: PipelineApplication[], query: PipelineQuery) {
  const keyword = query.keyword.trim().toLocaleLowerCase()
  const filtered = records.filter((application) => {
    const keywordFields = [
      application.candidateName,
      application.candidatePhone ?? '',
      application.jobTitle,
    ]
    return (
      (!keyword || keywordFields.some((value) => value.toLocaleLowerCase().includes(keyword))) &&
      (query.jobId === null || application.jobId === query.jobId) &&
      (!query.status || application.status === query.status)
    )
  })
  const start = (query.page - 1) * query.pageSize

  return {
    items: filtered.slice(start, start + query.pageSize),
    page: query.page,
    pageSize: query.pageSize,
    total: filtered.length,
  }
}

export function applyDemoStatusUpdate(
  application: PipelineApplication,
  request: PipelineStatusUpdateRequest,
  occurredAt = new Date().toISOString(),
) {
  if (application.status !== 'SUBMITTED' || request.toStatus !== 'SCREENING') {
    throw new Error('当前状态不能开始筛选')
  }

  return {
    ...application,
    status: request.toStatus,
    statusText: getApplicationStatusText(request.toStatus),
    ownerName: '当前 HR',
    hrNote: request.note || application.hrNote,
    lastActivityAt: occurredAt,
    timeline: [
      ...application.timeline,
      {
        id: `${application.id}-screening-${occurredAt}`,
        title: '进入 HR 筛选',
        description: request.note || 'HR 开始审核候选人资料。',
        actorName: '当前 HR',
        occurredAt,
        source: 'BUSINESS' as const,
        relatedObject: `投递 #${application.id}`,
      },
    ],
  }
}

export function applyDemoScreeningDecision(
  application: PipelineApplication,
  request: PipelineReviewRequest,
  occurredAt = new Date().toISOString(),
) {
  if (application.status !== 'SCREENING') throw new Error('只有筛选中的投递可以提交筛选结论')
  if (request.decision === 'REJECT' && (!request.rejectReasonCode || !request.note.trim())) {
    throw new Error('拒绝候选人必须选择原因并填写说明')
  }
  if (request.decision === 'PENDING' && !request.note.trim()) {
    throw new Error('保留待定时必须填写待核实事项')
  }

  const nextStatus = getScreeningDecisionStatus(request.decision)
  const actionText =
    request.decision === 'PASS'
      ? 'HR 确认初筛通过'
      : request.decision === 'REJECT'
        ? 'HR 确认初筛未通过'
        : 'HR 保留候选人为待定'

  return {
    ...application,
    status: nextStatus,
    statusText: getApplicationStatusText(nextStatus),
    reviewDecision: request.decision,
    hrNote: request.note.trim() || application.hrNote,
    rejectReasonCode: request.decision === 'REJECT' ? request.rejectReasonCode : null,
    rejectReason: request.decision === 'REJECT' ? request.note.trim() : null,
    lastActivityAt: occurredAt,
    timeline: [
      ...application.timeline,
      {
        id: `${application.id}-review-${occurredAt}`,
        title: actionText,
        description: request.note.trim() || 'HR 已完成本次筛选审核。',
        actorName: '当前 HR',
        occurredAt,
        source: 'BUSINESS' as const,
        relatedObject: `投递 #${application.id}`,
      },
    ],
  }
}
